/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fieldjetx.v2;

// import org.openqa.selenium.chrome.ChromeDriver;
// import io.github.bonigarcia.wdm.WebDriverManager;

public class App {
 

}